"""Add blog_templates table for template system

Revision ID: a873b24bd326
Revises: '2025_07_06_0005'
Create Date: 2025-07-06 23:09:24.928380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a873b24bd326'
down_revision = '2025_07_06_0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('estimated_duration', sa.String(), nullable=False),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('localization_level', sa.String(), nullable=True),
    sa.Column('is_boulet_style', sa.Boolean(), nullable=True),
    sa.Column('template_structure', sa.JSON(), nullable=False),
    sa.Column('sample_expressions', sa.JSON(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_blog_templates_id'), 'blog_templates', ['id'], unique=False)
    op.create_index(op.f('ix_blog_templates_name'), 'blog_templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_templates_name'), table_name='blog_templates')
    op.drop_index(op.f('ix_blog_templates_id'), table_name='blog_templates')
    op.drop_table('blog_templates')
    # ### end Alembic commands ###
