global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'geekblog-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alerts/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Container metrics from cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # FastAPI application metrics
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  # Celery worker metrics (if exposed)
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker:9540']
